spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: fight-response-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.iptgroup.BadgerFight.dto"
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: prWLypnNKuq6EPUncxciSOdhmzJo62mA8RaEqZiC9Sw=
