spring.application.name=BadgerFight

spring.datasource.username=${DB_USER}
spring.datasource.url=jdbc:postgresql://localhost:5432/badger_fight
#spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASSWORD}


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


server.port=8001

#client-id=springBootApplication
#resource-url=http://localhost:8080/realms/badger-fight/protocol/openid-connect/token
#grant-type=password
#
#spring.security.oauth2.client.registration.keycloak.client-id=springBootApplication
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.scope=openid
#
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/badger-fight
#spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/badger-fight